image: python:3.9

stages:
  - Static Analysis
  - Bootstrap
  - Build
  - Publish

linting:
  stage: Static Analysis
  before_script:
    - python --version
    - pip install pycodestyle
  script:
    - pycodestyle --format=pylint drf_keycloak_auth/

venv:
  stage: Bootstrap
  script:
    - make install-dependencies
  only:
    refs:
      - master

build:
  stage: Build
  script:
    - make
  only:
    refs:
      - master

pypi:
  stage: Publish
  script:
    - make publish-pypi
  only:
    refs:
      - tags
