image: python:3.9

stages:
  - Static Analysis
  - Bootstrap
  - Build
  - Publish

linting:
  stage: Static Analysis
  before_script:
    - python --version
    - pip install pycodestyle
  script:
    - pycodestyle --format=pylint drf_keycloak_auth/

venv:
  stage: Bootstrap
  script:
    - make install-dependencies
  artifacts:
    when: on_success
    expire_in: 1 hour
    paths:
      - venv/
  only:
    refs:
      - tags
      - master

build:
  stage: Build
  script:
    - make
  dependencies:
    - venv
  artifacts:
    when: on_success
    expire_in: 6 mos
    paths:
      - dist/
  only:
    refs:
      - tags
      - master

pypi:
  stage: Publish
  variables:
    TWINE_USERNAME: ${TWINE_USERNAME}
    TWINE_PASSWORD: ${TWINE_PASSWORD}
  script:
    - make publish-pypi
  only:
    refs:
      - tags
