version: '3.7'

services:
  test:
    build:
      context: .
    environment:
      DEBUG: 1
      DJANGO_LOG_LEVEL: 'DEBUG'
    env_file:
      - .env
    working_dir: /srv/app/
    volumes:
      - '.:/srv/app:cached'
    command: './manage.py runserver'