version: '3.7'

services:
  test:
    build:
      context: .
    environment:
      # django app config
      DEBUG: 1
      DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1]"
      KEYCLOAK_SERVER_URL: https://auth.dev.ecocommons.org.au/auth/
      KEYCLOAK_REALM: ecocommons-foobar
      KEYCLOAK_CLIENT_ID: local-dev-testing
      KEYCLOAK_CLIENT_SECRET_KEY: $KEYCLOAK_CLIENT_SECRET_KEY
      KEYCLOAK_MULTI_OIDC_JSON: $KEYCLOAK_MULTI_OIDC_JSON
      TEST_USERNAME: $TEST_USERNAME
      TEST_PASSWORD: $TEST_PASSWORD
    working_dir: /srv/app/
    volumes:
      - '.:/srv/app:cached'
    command: './manage.py test -v=2'