version: '3.7'

services:
  api:
    build:
      context: .
    environment:
      DEBUG: 1
      DJANGO_LOG_LEVEL: 'DEBUG'
    env_file:
      - .env
    expose:
      - '8000'
    ports:
      - 8000:8000
    working_dir: /srv/app/
    volumes:
      - '.:/srv/app:cached'
    command: 'bash -c "./manage.py migrate && ./manage.py runserver \"0.0.0.0:8000\""'